title: Survivor Team Go!
description: Support. Recover. Thrive.
logo: STG-artemisia-250.png

theme: jekyll-theme-cayman

links:
- title: home
  url: /
  external: false
- title: episodes
  url: /episodes
- title: about
  url: /about

defaults:
  - scope:
      path: '' # an empty string here means all files in the project
      type: 'posts'
    values:
      layout: 'episode'
      author: 'The Survivor Team'
      voices: 'Oliver Ayers', 'Bailey Davenport'
      # iTunes podcast metadata
      artist: The Survivor Team # artist or host
      album: Survivor Team Go! # title of podcast
      genre: personal journals # is this one of them?
      copyright: The Survivor Team # ???
      album art: site.logo # did i do this right?
